#pragma once

#include <nre/prerequisites.hpp>

#include <nre/rendering/newrg/render_pipeline.hpp>
#include <nre/rendering/newrg/delegable_render_factory.hpp>
#include <nre/rendering/newrg/delegable_render_factory_proxy.hpp>
#include <nre/rendering/newrg/render_frame_allocator.hpp>
#include <nre/rendering/newrg/render_frame_containers.hpp>
#include <nre/rendering/newrg/render_graph.hpp>
#include <nre/rendering/newrg/render_path.hpp>
#include <nre/rendering/newrg/abytek_render_path.hpp>
#include <nre/rendering/newrg/abytek_render_factory_proxy.hpp>
#include <nre/rendering/newrg/render_pass.hpp>
#include <nre/rendering/newrg/render_pass_id.hpp>
#include <nre/rendering/newrg/render_resource.hpp>
#include <nre/rendering/newrg/render_resource_id.hpp>
#include <nre/rendering/newrg/external_render_resource.hpp>
#include <nre/rendering/newrg/render_resource_state.hpp>
#include <nre/rendering/newrg/render_resource_producer_dependency.hpp>
#include <nre/rendering/newrg/render_resource_consumer_dependency.hpp>
#include <nre/rendering/newrg/render_resource_access_dependency.hpp>
#include <nre/rendering/newrg/render_resource_allocator.hpp>
#include <nre/rendering/newrg/render_resource_barrier_batch.hpp>
#include <nre/rendering/newrg/rhi_placed_resource_pool.hpp>
#include <nre/rendering/newrg/rhi_frame_buffer_pool.hpp>
#include <nre/rendering/newrg/main_render_worker.hpp>
#include <nre/rendering/newrg/render_pass_functor.hpp>
#include <nre/rendering/newrg/render_pass_flag.hpp>
#include <nre/rendering/newrg/render_pass_id_range.hpp>
#include <nre/rendering/newrg/render_pass_execute_range.hpp>
#include <nre/rendering/newrg/render_fence_state.hpp>
#include <nre/rendering/newrg/render_fence_batch.hpp>
#include <nre/rendering/newrg/command_list_pool.hpp>
#include <nre/rendering/newrg/command_list_batch.hpp>
#include <nre/rendering/newrg/managed_command_list_batch.hpp>
#include <nre/rendering/newrg/managed_fence_batch.hpp>
#include <nre/rendering/newrg/managed_render_work.hpp>
#include <nre/rendering/newrg/render_foundation_events.hpp>
#include <nre/rendering/newrg/render_foundation.hpp>
#include <nre/rendering/newrg/render_resource_aliasing_state.hpp>
#include <nre/rendering/newrg/descriptor_allocator.hpp>
#include <nre/rendering/newrg/descriptor_allocation.hpp>
#include <nre/rendering/newrg/descriptor_page.hpp>
#include <nre/rendering/newrg/descriptor_placed_range.hpp>
#include <nre/rendering/newrg/intermediate_descriptor_manager.hpp>
#include <nre/rendering/newrg/descriptor_handle_range.hpp>
#include <nre/rendering/newrg/render_descriptor.hpp>
#include <nre/rendering/newrg/render_descriptor_element.hpp>
#include <nre/rendering/newrg/render_descriptor_id.hpp>
#include <nre/rendering/newrg/external_render_descriptor.hpp>
#include <nre/rendering/newrg/render_frame_buffer.hpp>
#include <nre/rendering/newrg/render_frame_buffer_id.hpp>
#include <nre/rendering/newrg/external_render_frame_buffer.hpp>
#include <nre/rendering/newrg/general_resource_uploader.hpp>
#include <nre/rendering/newrg/transient_resource_uploader.hpp>
#include <nre/rendering/newrg/transient_resource_readback.hpp>
#include <nre/rendering/newrg/render_graph_late_setup_functor.hpp>
#include <nre/rendering/newrg/render_binder_group.hpp>
#include <nre/rendering/newrg/render_binder_group_id.hpp>
#include <nre/rendering/newrg/render_binder_group_functor.hpp>
#include <nre/rendering/newrg/render_binder_group_signatures.hpp>
#include <nre/rendering/newrg/binder_signature_manager.hpp>
#include <nre/rendering/newrg/binder_signature.hpp>
#include <nre/rendering/newrg/binder_signature_all_1cbv.hpp>
#include <nre/rendering/newrg/binder_signature_vs_1cbv_ps_1cbv.hpp>
#include <nre/rendering/newrg/binder.hpp>
#include <nre/rendering/newrg/render_bind_list.hpp>
#include <nre/rendering/newrg/external_render_bind_list.hpp>
#include <nre/rendering/newrg/gpu_driven_stack.hpp>
#include <nre/rendering/newrg/cpu_gpu_data_pool.hpp>
#include <nre/rendering/newrg/scene_render_view.hpp>
#include <nre/rendering/newrg/render_path.hpp>
#include <nre/rendering/newrg/render_actor_data_pool.hpp>
#include <nre/rendering/newrg/unified_mesh.hpp>
#include <nre/rendering/newrg/unified_mesh_data.hpp>
#include <nre/rendering/newrg/unified_mesh_asset.hpp>
#include <nre/rendering/newrg/unified_mesh_asset_factory.hpp>
#include <nre/rendering/newrg/unified_mesh_builder.hpp>
#include <nre/rendering/newrg/unified_mesh_system.hpp>
#include <nre/rendering/newrg/unified_mesh_drawable.hpp>
#include <nre/rendering/newrg/unified_mesh_material.hpp>
#include <nre/rendering/newrg/bind_list.hpp>
#include <nre/rendering/newrg/rhi_resource_view_bind.hpp>
#include <nre/rendering/newrg/render_pass_utilities.hpp>
#include <nre/rendering/newrg/page_resource_stream.hpp>
#include <nre/rendering/newrg/gpu_large_data_list.hpp>
#include <nre/rendering/newrg/gpu_page_based_uploader.hpp>
#include <nre/rendering/newrg/gpu_range_based_uploader.hpp>
#include <nre/rendering/newrg/cacheable_pool_gpu_data_table.hpp>
#include <nre/rendering/newrg/uncacheable_pool_gpu_data_table.hpp>
#include <nre/rendering/newrg/general_gpu_data_table.hpp>
#include <nre/rendering/newrg/gpu_data_table_render_bind_list.hpp>
#include <nre/rendering/newrg/render_actor_data.hpp>
#ifdef NRE_ENABLE_ASYNC_COMPUTE
#include <nre/rendering/newrg/async_compute_render_worker.hpp>
#endif