#pragma once

#include <nre/prerequisites.hpp>

#include <nre/rendering/newrg/render_pipeline.hpp>
#include <nre/rendering/newrg/render_frame_allocator.hpp>
#include <nre/rendering/newrg/render_frame_containers.hpp>
#include <nre/rendering/newrg/render_graph.hpp>
#include <nre/rendering/newrg/render_pass.hpp>
#include <nre/rendering/newrg/render_pass_id.hpp>
#include <nre/rendering/newrg/render_resource.hpp>
#include <nre/rendering/newrg/render_resource_id.hpp>
#include <nre/rendering/newrg/external_render_resource.hpp>
#include <nre/rendering/newrg/render_resource_state.hpp>
#include <nre/rendering/newrg/render_resource_producer_dependency.hpp>
#include <nre/rendering/newrg/render_resource_consumer_dependency.hpp>
#include <nre/rendering/newrg/render_resource_access_dependency.hpp>
#include <nre/rendering/newrg/render_resource_allocator.hpp>
#include <nre/rendering/newrg/render_resource_barrier_batch.hpp>
#include <nre/rendering/newrg/rhi_placed_resource_pool.hpp>
#include <nre/rendering/newrg/rhi_frame_buffer_pool.hpp>
#include <nre/rendering/newrg/main_render_worker.hpp>
#include <nre/rendering/newrg/render_pass_functor.hpp>
#include <nre/rendering/newrg/render_pass_flag.hpp>
#include <nre/rendering/newrg/render_pass_id_range.hpp>
#include <nre/rendering/newrg/render_pass_execute_range.hpp>
#include <nre/rendering/newrg/render_fence_state.hpp>
#include <nre/rendering/newrg/render_fence_batch.hpp>
#include <nre/rendering/newrg/command_list_pool.hpp>
#include <nre/rendering/newrg/command_list_batch.hpp>
#include <nre/rendering/newrg/managed_command_list_batch.hpp>
#include <nre/rendering/newrg/managed_fence_batch.hpp>
#include <nre/rendering/newrg/managed_render_work.hpp>
#include <nre/rendering/newrg/renderer_events.hpp>
#include <nre/rendering/newrg/renderer.hpp>
#include <nre/rendering/newrg/render_resource_aliasing_state.hpp>
#include <nre/rendering/newrg/descriptor_allocator.hpp>
#include <nre/rendering/newrg/descriptor_allocation.hpp>
#include <nre/rendering/newrg/descriptor_page.hpp>
#include <nre/rendering/newrg/descriptor_placed_range.hpp>
#include <nre/rendering/newrg/intermediate_descriptor_manager.hpp>
#include <nre/rendering/newrg/descriptor_handle_range.hpp>
#include <nre/rendering/newrg/render_descriptor.hpp>
#include <nre/rendering/newrg/render_descriptor_id.hpp>
#include <nre/rendering/newrg/external_render_descriptor.hpp>
#include <nre/rendering/newrg/render_frame_buffer.hpp>
#include <nre/rendering/newrg/render_frame_buffer_id.hpp>
#include <nre/rendering/newrg/external_render_frame_buffer.hpp>
#include <nre/rendering/newrg/general_resource_uploader.hpp>
#include <nre/rendering/newrg/transient_resource_uploader.hpp>
#ifdef NRE_ENABLE_ASYNC_COMPUTE
#include <nre/rendering/newrg/async_compute_render_worker.hpp>
#endif